

```{r}
df <- read.csv('./data/visualisation.csv')
```


```{r}
head(df)
```

```{r}
library(ggplot2)
```

```{r}
ggplot(df, aes(x = explicitness, y = popularity)) +
  geom_boxplot()
```

```{r}
df$release_date <- as.Date(df$release_date)

ggplot(df, aes(x = release_date, y = lexical_richness, colour = markets)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = "lm") +
  scale_x_date(
    limits = as.Date(c("2000-01-01", "2024-01-01"))
  ) +
  ylim(0, 100)
```

```{r}
ggplot(df, aes(release_date, fill = explicitness)) +
  geom_density(position = "stack")
```

```{r}
ggplot(df, aes(release_date, after_stat(count), fill = markets)) +
  geom_density(position = "fill")
```

```{r}
diamonds
```

```{r}
density <- ggplot(df, aes(x = lexical_richness, y = sentiment_compound)) +
 geom_point() +
 geom_density_2d() +
 geom_density_2d_filled(alpha = 0.5) +
 geom_density_2d(linewidth = 0.25, colour = "black")

 density
```

```{r}
density + facet_wrap(vars(markets))
```

```{r}
head(faithful)
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```